#! /bin/sh

case "$1" in
	start)
		echo "Starting aesdchar load"
		/bin/aesdchar_load
		;;
	stop)
		echo "Removing aesdchar unload"
		/bin/aesdchar_unload
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac
exit 0